### ISSUE TITLE
Track Player Stats

### ISSUE THREAD

**Issue by Tilier** [tylermurphy534/KenshinsHideAndSeek#17]
**Is your feature request related to a problem? Please describe.**
No, it's not an issue. I just think it would be cool if there was a way to get player stats.

**Describe the solution you'd like**
Perhaps a `/stats [player]` command that gives you the wins and losses of a player? And then possibly a `/leaderboard` command too. However, this might be difficult for people using other plugins and stuff for things like stats and a leaderboard. For instance, I use Skript a lot in my server, and would probably want to code my own command and stuff.

**Describe alternatives you've considered**
I honestly have no idea how I would do this.

**Additional context**
Nothing else!

**Comment by tylermurphy534** [comment]
Hello Tillier,

Ive been thinking about adding this. I think that there should be two commands added. `/hs top <page>` and `/hs wins <player>`. This way you can get individual player wins, and also a leaderboard. Would this work for you?

**Comment by Tilier** [comment]
Yeah, that would be great!! Maybe a way to see losses too, or like a winning percentage, but I'm not sure. Thanks so much!!

**Comment by tylermurphy534** [comment]
I'm adding win amounts as each role, and total games played. Feature should be added in 1.3.3 betas soon. Marking issue as closed.
