### ISSUE TITLE
Adding player firendly lobby/game use.

### ISSUE THREAD

**Issue by CrazyCloudCraft** [tylermurphy534/KenshinsHideAndSeek#24]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. Ex. I'm always frustrated when players come into the lobby, and they have to klick npc (that i created) to start the game or leaveing it. (there may be more commands that i not mention here, but they are also mentioned).

**Describe the solution you'd like**

That in the lobby everyone get's a bed to leave on the 9 inventory slot and on the 1 slot the player can start the game, if there are enough players. On the 5 slot there could be opened a gui there you can get a higher chance to be a Seeker for example. (But every item can enabled or disabled or changed (the item or the inventory slot) by the config).

**Describe alternatives you've considered**

There is no other solution. Sorry.

**Additional context**
  
![2022-04-20_21 08 09](https://user-images.githubusercontent.com/95505222/164304658-49d03c1d-2f1c-43fc-833e-1607d29eb0b7.png)

**Comment by CrazyCloudCraft** [comment]
But hey, i fought that the plugin would not anymore updated, i'm surprisd.

**Comment by tylermurphy534** [comment]
Dear CrazyCloudCraft,

Yeah I can totally implement this. I've currently been working on multi map support for a lobby, but its been way more complex than I thought (for how I want to implement it that is). For time being I can add a bed in the 9th slot that runs `/hs leave` for the player, and some other item to start the game using `/hs start` for admins. And everything can be completely customized of course.

Second, what did you mean by your second comment? Is the plugin not working when you updated to a newer version?

Thank you for your input.

Sincerely,

Tyler Murphy

**Comment by CrazyCloudCraft** [comment]
Yes, you may add an item to change the lobby. But a command for lobby changeing would be also great.

**Comment by CrazyCloudCraft** [comment]
> Dear CrazyCloudCraft,
> 
> Yeah I can totally implement this. I've currently been working on multi map support for a lobby, but its been way more complex than I thought (for how I want to implement it that is). For time being I can add a bed in the 9th slot that runs `/hs leave` for the player, and some other item to start the game using `/hs start` for admins. And everything can be completely customized of course. I'm currently not sure about another Item that changes seeker percentages, but I can look more into that in the future.
> 
> Second, what did you mean by your second comment? Is the plugin not working when you updated to a newer version?
> 
> Thank you for your input.
> 
> Sincerely,
> 
> Tyler Murphy

The plugin has since v1.3.3 a long time without plugin updates, (and it completely killed my server with this EntityDamageEvent xD,)

**Comment by tylermurphy534** [comment]
Dear CrazyCloudCraft,

A 1.4.2 Beta has been uploaded to the repository. You can download a compiled jar on the actions section of the repo. I added the lobby icons that you suggested. I also made /hs leave toggleable from just teleporting to the exit location, to also allowing bungee/velocity to teleport to a hub server.

If you find any bugs, please comment them in a new issue.  And since this suggestion has been added in a beta and is set for future release, I will close this issue.

Thank you!

Sincerely,

Tyler Murphy
