### ISSUE TITLE
Bug Report: Can't change leaderboard title.

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#28]
**Describe the bug**
You cannot change the title of the leaderboard, it will always be yellow "HIDE AND SEEK"

**To Reproduce**
1. Change title of leaderboard
2. /hs reload and you'll see it's still the same as default.

**Expected behavior**
It should update to what I put in my leaderboard.yml

**Screenshots**
-

**System Info (please complete the following information):**
 - OS: [e.g. Windows/Linux] windows
 - Server Host [e.g. Apex/Custom] custom
 - MC Version [e.g. 1.17/1.18] 1.18.2
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] 1.4.2

**Additional context**
-

**Comment by tylermurphy534** [comment]
Open your localization.yml file. Is it only displaying as ? in game, or has the file also changed to ?. If the file changed, can you tell me if the file itself (not the messages in game) changes to ? after the first reload or the second.

Thanks!

**Comment by tylermurphy534** [comment]
Also, does this only happen in the localization.yml file, or does it also happen in items.yml. I do not care about config.yml and leaderboard.yml in this situation as they are loaded and saved in the same way as localization.yml. Only items.yml is different.

**Comment by tylermurphy534** [comment]
Is this only happening in the lobby scoreboard, or also the in game scoreboard? If its just the lobby, I found the issue and am pushing it to a 1.4.3 beta you can download on the Actions page of this repo.

**Comment by Nesseley** [comment]
It was both, but they seem to be fixed now! Thanks! :D
