### ISSUE TITLE
Feature Request: Add option to change what sound plays on SeekerPing

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#29]
**Is your feature request related to a problem? Please describe.**
The problem is that the sound is very loud, and it makes sense to be able to choose sound your self. 
The setting in itself also seems broken, as enabled: false does nothing.

**Describe the solution you'd like**
Adds option to set sound and sound levels for SeekerPing.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by tylermurphy534** [comment]
Added in new 1.4.3 beta

**Comment by tylermurphy534** [comment]
I fixed this btw lol

**Comment by Nesseley** [comment]
Yes, I just haven't tested it yet :D x)

**Comment by Nesseley** [comment]
It seems to be working, but what is the difference between heartbeatNoise and ringingNoise?
I set heartbeat to a new sound, but there was no ringingNoise (which should have been a diffrent sound)

```
    heartbeatNoise: "ENTITY_CHICKEN_EGG"
    ringingNoise: "BLOCK_NOTE_BLOCK_PLING"

**Comment by tylermurphy534** [comment]
what is your seeker ping level 2 or level 3 in the config?

**Comment by tylermurphy534** [comment]
Uploaded fix on new build, try it now

**Comment by Nesseley** [comment]
Fixed :)
