### ISSUE TITLE
Feature Request: Option to throw people to exit after game end

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#30]
**Is your feature request related to a problem? Please describe.**
I would like for players to be sent out to the exit and leave the game once it ends, either it is by winning, loosing or times up.

**Describe the solution you'd like**
Option `leave-on-end: true/false` to be added to the config.

**Describe alternatives you've considered**
-

**Additional context**
I find it quite confusing as to why it doesn't send them out of the game, I know 100% my players will be confused as how to leave since we don't use commands to join. It's also typical behavior to be sent back to the main lobby and exit the minigame after a game (in my head atleast!)

**Comment by Nesseley** [comment]
Another thing that will be an issue here is that with many players some are bound to be AFK at some point. What if they get the seeker role on the next round? Then the whole lobby has to wait for the time to run out.

**Comment by tylermurphy534** [comment]
Added the leaveOnEnd to latest beta build. 

I have to think of an AFK fix in the future, as many people 'hiding' may be mistaken as AFK. I have to figure out an solution that doesnt hurt gameplay, but helps your problem.

**Comment by Nesseley** [comment]
Great work! :D Definitively fixes my problem :)
