### ISSUE TITLE
Feature request: Missing option to configure glow item and description for it

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#31]
**Is your feature request related to a problem? Please describe.**
There no way to translate the stuff that's on the Glow item.

**Describe the solution you'd like**
Add option to customize the glow items name, lore and item ID.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by tylermurphy534** [comment]
Added in new 1.4.3 beta

**Comment by Nesseley** [comment]
Amazing!
