### ISSUE TITLE
Feature request: Missing option to change title of class-selection

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#32]
**Is your feature request related to a problem? Please describe.**
When the game starts and you get a role, theres no option to translate de "SEEKER" and "HIDER" main part of the title.
You can however define the subtitles "HIDERS_SUBTITLE:" "SEEKERS_SUBTITLE:"

**Describe the solution you'd like**
Add option to translate the main title of role-titles.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by tylermurphy534** [comment]
Added HIDER_TEAM_NAME and SEEKER_TEAM_NAME to localization.yml files in 1.4.3 betas

**Comment by Nesseley** [comment]
Would that be this file? https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2265236385 I'l test to see if it works :)

**Comment by Nesseley** [comment]
Fixed in 1.4.3 betas 👍
