### ISSUE TITLE
Feature request: Option to define the name of the team in Scoreboard

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#33]
**Is your feature request related to a problem? Please describe.**
I'm translating everything into norwegian, but the scoreboard still shows it as "SEEKER" and "HIDER" on the team: part.

**Describe the solution you'd like**
Add a way to rename the teams.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by tylermurphy534** [comment]
You can change this all in leaderboard.yml. The entire scoreboard is customizable!!!!!

**Comment by Nesseley** [comment]
No, i'm pretty sure I can't change this part.. If I am please tell me what line. :/  I am talking about this:
```
game:
  title: "&eGjemsel"
  content: [
    "Lag: {TEAM}",
```
    It's the {TEAM} thing that will show in english
    
![image](https://user-images.githubusercontent.com/11998470/166692859-1ce63754-8181-496c-be8b-039bfdd3dac0.png)

**Comment by tylermurphy534** [comment]
Fixed in a newer build of 1.4.3. It uses the team names found in the localization file.

**Comment by Nesseley** [comment]
Fixed 👍
