### ISSUE TITLE
Bug report: Setting some settings to false does nothing

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#37]
**Describe the bug**
announceMessagesToNonPlayers: false still sends messages to everyone online.
pvp: false still have pvp on and you need to hit people multiple times, and hiders can fight back.

**To Reproduce**
Set stuff to false :(

**Expected behavior**
I expect what the config tells me `false` will do.

**Screenshots**
-

**System Info (please complete the following information):**
 - OS: [e.g. Windows/Linux] windows
 - Server Host [e.g. Apex/Custom] custom
 - MC Version [e.g. 1.17/1.18] 1.18.2
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] 1.4.3

**Additional context**
-

**Comment by tylermurphy534** [comment]
Found an issue where i was loading ALL booleans from ANY config file incorrectly. Oops.

Fixing in next 1.4.3 beta, should be uploaded soon.

**Comment by Nesseley** [comment]
Let me know when and I'l test it out :)

**Comment by Nesseley** [comment]
`announceMessagesToNonPlayers: false`: Fixed
`pvp: false` fixed - but new "bug"

When hitting the Seeker it will send the GAME_PLAYER_DEATH message from localization.

**Comment by tylermurphy534** [comment]
Fix in beta 3 of 1.4.3 :) (hopefully)

**Comment by Nesseley** [comment]
Doesn't seem fixed using this build: https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2270516318

**Comment by tylermurphy534** [comment]
Uploaded new build

**Comment by Nesseley** [comment]
Seems fixed! :)
