### ISSUE TITLE
Bug report: Can't remove lore on leave item

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#38]
**Describe the bug**
If you try to set the lore of the leave item to [] and use /hs reload it will just put back the default lore.

**To Reproduce**
1. Remove lore
2. reload

**Expected behavior**
To not show any lore.

**Screenshots**
-
**System Info (please complete the following information):**
 - OS: [e.g. Windows/Linux] windows
 - Server Host [e.g. Apex/Custom] custom
 - MC Version [e.g. 1.17/1.18] 1.18.2
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] 1.4.3

**Additional context**
-

**Comment by tylermurphy534** [comment]
Fixed in newest build

**Comment by Nesseley** [comment]
:D
