### ISSUE TITLE
Bug report: Glow-snowball is kept in inventory after getting killed by a seeker.

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#41]
**Describe the bug**
If you get killed by a seeker with the glow-snowball in your inventory it will not be cleared when you respawn as a seeker.

**Expected behavior**
The snowball should disapear.

**System Info (please complete the following information):**
 - OS: [e.g. Windows/Linux]
 - Server Host [e.g. Apex/Custom]
 - MC Version [e.g. 1.17/1.18]
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] 1.4.3 https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2301151823

**Comment by tylermurphy534** [comment]
forgot to reset seekers inv when rewriting the player death event, should be fixed now
