### ISSUE TITLE
Bug Report: Leaving the game while in "countdown" mode doesn't reset the start

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#43]
**Describe the bug**
joining a game, starting it with the clock and then leaving before the countdown ends doesn't reset the timer, so if you join again with /hs join it still thinks you're the seeker and you can't move. It also counts down on the right scoreboard. But you get the items to start a new round or leave.

**To Reproduce**
1. Start a round
2. Leave
3. Join again

**Expected behavior**
The game should stop if everyone leaves.

**System Info (please complete the following information):**
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2303287291

**Comment by tylermurphy534** [comment]
So when you leave as a seeker, does the game stop, or just the starting countdown keep going? And if it stops, if you rejoin as seeker, does the starting countdown resume, or do you just get effects for a bit before being teleported to the lobby?

**Comment by Nesseley** [comment]
1. Join the game with 2 users and start it.
2. Once the teams have been given out and the countdown had started. The seeker leaves with /hs leave
The hider will get the "every seeker left the game" message and be sent to the Exit.

3. Now join back in with the user who was Seeker.
The seeker will be unable to move or see. And items are given out like if you are starting a new round.
4. (Join with a second user to do the next part) If the bugged seeker right clicks with the clock(start item) the players will be reassigned roles, but the timer in scoreboard will show 20 minutes, you still get the title text with "hide in x seconds" and when the 30 seconds are up the time will start counting down in the scoreboard from 20.

**Comment by tylermurphy534** [comment]
What items are given out? The lobby items, or game items?

**Comment by tylermurphy534** [comment]
Try it now on new build
