### ISSUE TITLE
Bug Report: Broken placeholder for seeker-deaths and hider-deaths

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#45]
**Describe the bug**
I already reported this in another ticket, but I think it deserves it's own ticket. So it's not lost somewhere :) 

This placeholder seems a bit weird: `%hs_stats_seeker-deaths%`

I don't have PVP enabled, so in theory the seeker can't die. But the number goes up when I'm playing games. 
I was just killed as a hider and `%hs_stats_hider-deaths%` did not change, but seeker-deaths did, so it seems to register on the wrong stats.

**To Reproduce**
1. Start as a hider.
2. Get killed, then kill another player.
3. It saves it as a "death as a seeker" since you now are a seeker

**Expected behavior**
It should be saved as a death as hider, since that's is what I was when I died.

**System Info (please complete the following information):**
 - OS: [e.g. Windows/Linux] windows
 - Server Host [e.g. Apex/Custom] custom
 - MC Version [e.g. 1.17/1.18] 1.18.2
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2303287291

**Comment by tylermurphy534** [comment]
uploaded new build!

**Comment by Nesseley** [comment]
I didn't get any stats at all when killing someone while starting as the seeker.

**Comment by tylermurphy534** [comment]
I accidentally tested for kills on the player who dies instead of the attacker, fixed now

**Comment by Nesseley** [comment]
Now theres some other bug haha

`Sjokoladeku` was the seeker this round and killed `Nesseley`

**Comment by tylermurphy534** [comment]
uploaded a new build that hopefully fixes it

**Comment by Nesseley** [comment]
Seems fixed! :D Great work! 🎉
