### ISSUE TITLE
Bug Report: Broken placeholder for hider-games and seeker-games

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#46]
**Describe the bug**
Every game gets registered as a seeker game. 

**To Reproduce**
1. Start a game as hider.
2. Die, and become a seeker.
3. Game ends and you get stats on the `%hs_stats_seeker-games%` placeholder.

**Expected behavior**
You should only get stats for the team you started as. 
If I start a a hider I want the stats to go up on the `&hs_stats_hider-games%` and if I start as a seeker `%hs_stats_seeker-games%`
It shouldn't matter that I died as a hider, it was still a hider game.

**System Info (please complete the following information):**
 - OS: [e.g. Windows/Linux] windows
 - Server Host [e.g. Apex/Custom] custom
 - MC Version [e.g. 1.17/1.18] 1.18.2
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2303287291

**Comment by tylermurphy534** [comment]
uploaded new build!

**Comment by Nesseley** [comment]
Still got stats on the `%hs_stats_seeker-games%` even though I started as a hider

**Comment by tylermurphy534** [comment]
forgot to do first seeker check lol, changed now
