### ISSUE TITLE
Bug Report: Game abandoned still counts as a win.

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#47]
**Describe the bug**
If all the players leave before the game has started (or during the round for that matter) it still saves stats as if you have played and won the game.
It count's toward `%hs_stats_total-wins%` (and the team you were on), `%hs_stats_total-games%` (and the team you were on)

**To Reproduce**
1. Start a game with 2 users.
2. Leave with one of the users.
3. Check stats for the user who didn't leave.

**Expected behavior**
It shouldn't save any stats at all if the game ends by all players leaving it.

Not sure what should happen if a player leaves a game but the game goes on since there's more players playing. 
It would be fair to keep the stats (so they can't leave because they died and not get stats (cheating)) 
But what if you just happen to be the first to leave, then everyone else leaves too? That would be an abandoned game by everyone, and all the stats should be wiped?

Maybe stats needs to only be updated on game end (if it's not already)

**Comment by tylermurphy534** [comment]
hopefully fixed in new build, also added GAME_GAMEOVER_HIDERS_QUIT in localization.yml

**Comment by Nesseley** [comment]
When I left as the hider it sent the `GAME_GAMEOVER_HIDERS_FOUND` message and didn't send `GAME_GAMEOVER_HIDERS_QUIT` at all

**Comment by tylermurphy534** [comment]
Uploaded a new build. You also might of swapped the two messages in the localization file on accident.

**Comment by Nesseley** [comment]
Seems good now! 👍
