### ISSUE TITLE
Feature request: Time played statistic

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#48]
**Describe the solution you'd like**
Add statistic and placeholders for time played in hide and seek.

`total time played`
`time played as seeker`
`time played as hider`

It could be saved and displayed in seconds, and then people can just use the papi math expansion to format how they like. 

It should only count time when the game is active (not lobby fase)

**Comment by tylermurphy534** [comment]
Repo moved
https://git.tylermurphy.net/tylermurphy534/KenshinsHideAndSeek/issues
