### ISSUE TITLE
Bug Report: START_COUNTDOWN shouldn't send prefix if the hideCountdownDisplay is set to "TITLE"

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#49]
**Describe the bug**
Not really a bug, but a minor annoyance.

When displaying the Title it will send the `default prefix` from config.yml in the beginning of the title. This just looks weird and takes up more space on the screen :)

**Expected behavior**
It should just send the `START_COUNTDOWN` from `localization.yml` without the prefix.

**Comment by tylermurphy534** [comment]
fixed in latest build

**Comment by Nesseley** [comment]
Indeed fixed! :)
