### ISSUE TITLE
Move CONTRIBUTING.md to root directory

### ISSUE THREAD

**Issue by bobby29831** [tylermurphy534/KenshinsHideAndSeek#52]
Not a bug, but something that __needs__ to be changed.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/84546230/168196601-2ad6fc67-e3bf-4c89-b9ee-63c86089d3d5.png">

No one is going to look in the folder meant for GitHub workflow and templates for a file that dictates how you should do things. I looked for a CONTRIBUTING.md, and found none because it wasn't in the proper place.

**Comment by tylermurphy534** [comment]
fixed!
