### ISSUE TITLE
Better structured commands

### ISSUE THREAD

**Issue by bobby29831** [tylermurphy534/KenshinsHideAndSeek#56]
**Is your feature request related to a problem? Please describe.**
Not a problem, but something that could be implemented to make working with/setting up the plugin easier.

**Describe the solution you'd like**
I'm proposing commands could be rewritten with a command library, [TriumphCMDs ](https://triumphteam.dev/library/triumph-cmds/introduction)that I'm familiar with and I could do all of it myself. This overhaul would allow the plugin to more easily work with different arguments and flags which could make the user experience easier and make it very clear what everything is doing. It would also allow for much greater simplified logic with some commands as a lot of complex logic is due to the structuring of commands.

**Example Changes**
```
/hs setexit, /hs setlobby, /hs setspawn ----> /hs set <exit|lobby|spawn> 
/hs setborder ----> /hs border [ONE|TWO] [-s]
```

The set location commands in this example would be concatenated to one command with the option to change parameters which automatically gets rid of some classes and nearly duplicated logic. The set border command becomes a simpler to work with command as you have to set both points by choosing which to run at a certain time, and then after (or during) when you want to reset the points based on the points stored, you can add the -s flag which means to actually set the position. This change would just make it more friendly to work with an understand what the plugin is doing when setting the border.

The overhaul would involve similar changes for other commands where it would be necessary.

**Describe alternatives you've considered**
Not really applicable to this proposition, but we could use a different library if you want.

**Additional context**
Just interested in feedback about this being done before I start doing it because it's a larger task.

**Comment by tylermurphy534** [comment]
It does seem like a nice library at first glance. Though I have a few questions. Can you customize the error messages it sends? And can you make it run a certain command if no arguments are passed into `/hs`? If both are yes, then sure why not!

**Comment by bobby29831** [comment]
You can customize messages for issues with permission and for commands that are supposed to be used by players only and console only by utilizing this structure...
```java
BukkitCommandManager.registerMessage(BukkitMessageKey.NO_PERMISSION, (sender, context) -> {});
```
You run into more trouble when trying to configure error messages on syntax or argument errors, but the messages that the library provides suffice. However, I do think making them configurable is largely unnecessary since the messages already provided are nice looking and error messages looking nice are usually to the least concern of everyone.

It's really easy to declare default command behavior through the `@Default` annotation. It can be applied to methods that are subcommands or just naked methods and defines the default behavior if the command is executed with no subcommands.
```java
@Command(value = "hs", alias = {"hideandseek"})
public class ParentCommand {

    @Default
    @SubCommand(value = "help", alias = {"?"})
    @Permission("hideandseek.help")
    public void help(CommandSender sender) {
        ...
    }

}
```
This class for example creates the command `/hs` (or `/hideandseek`) with the subcommand `/hs help` (or `/hs ?`) that requires the sender to have the permission `hideandseek.help` and will be executed if the command `/hs` or `/hs help` is run.

```java
@Command(value = "hs", alias = {"hideandseek"})
public class ParentCommand {

    @Default
    @Permission("hideandseek.help")
    public void help(CommandSender sender) {
        ...
    }

}
```
In this case where the `@SubCommand` annotation is withheld, it would run in the exact same manner, but just not with `/hs help` (or `/hs ?`).

**Comment by bobby29831** [comment]
After more investigation, it's simple to modify the other messages I just hadn't found where to look. (The rewritten documentation is still fairly young so I had to dig through source code). Here's the full list of messages that you can change...

 - `UNKNOWN_COMMAND`
 - `TOO_MANY_ARGUMENTS`
 - `NOT_ENOUGH_ARGUMENTS`
 - `INVALID_ARGUMENT`
 - `MISSING_REQUIRED_FLAG`
 - `MISSING_REQUIRED_FLAG_ARGUMENT`
 - `INVALID_FLAG_ARGUMENT`
 - `NO_PERMISSION`
 - `PLAYER_ONLY`
 - `CONSOLE_ONLY`

**Comment by tylermurphy534** [comment]
Okay cool! The only reason I want custom messages is so people can change them to different languages in localization.yml. Also, the default command Is supposed to be `/hs about` not `/hs help`.

But besides that, It looks good, and you can go ahead and implement it if you want.
