### ISSUE TITLE
Bug report: Stats for seeker-kills doesn't save if you get them after you've been a hider.

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#57]
**Describe the bug**
If you start as a hider, then gets found and you then kill people as a seeker, they don't register.

**To Reproduce**
1. Start as a hider, then be found.
2. Now you're a seeker. Go get some kills.
3. Game win/loss, see you've got no statistics for the kills you did.

**Expected behavior**
The player should get statistics for the kills he/she got when seeker, even if they started as a hider.

**Comment by tylermurphy534** [comment]
This was intentional, as I only wanted to save stats for the original team you were on. I can change this if you want, but this isn't a bug.

**Comment by tylermurphy534** [comment]
Added in the latest build, 1.4.3 RC1.
