### ISSUE TITLE
Feature request: Add a separate line for countdown 1 second, and add 4 seconds to the countdown.

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#58]
**Describe the solution you'd like**
**1:** I would like to format the 1 second remaining line different from the rest.
`2 seconds remaining` `1 second remaining`

**2:** With the addition of title and actionbar countdowns it looks weird when it skips from 5 seconds remaining to 3, 2, 1. Add 4 seconds to the countdown as well.

**Comment by tylermurphy534** [comment]
Added in newest build

**Comment by tylermurphy534** [comment]
Added in the latest build, 1.4.3 RC1.

**Comment by Nesseley** [comment]
Works 👍
