### ISSUE TITLE
Feature request: Always glow

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#59]
**Describe the solution you'd like**
It would be nice with a new option: `always-glow: true/false` which defaults to `false`.
If set to true, all seekers should be glowing with no time-limit. The glow item also wouldn't be given to hiders.

**Comment by tylermurphy534** [comment]
Added in the latest build, 1.4.3 RC1. 

I will not be adding any new features until I finalize this release as I just want to get it out lol.

**Comment by Nesseley** [comment]
Works! :)

Understandable, I really appreciate your hard work! :)
