### ISSUE TITLE
Bug report: Righthanded Scoreboard doesn't update when game starts.

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#60]
**Describe the bug**
The scoreboard to the right on the screen doesn't change from `waiting for players to join` to the `team: <team>`

**Expected behavior**
The scoreboard used to show what team you were on once the countdown started.

**System Info (please complete the following information):**
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2349216702

**Comment by tylermurphy534** [comment]
Is this countdown you're talking about the countdown in the lobby? If it is, then yeah, thats how its supposed to work. If its the countdown while people are hiding, then yeah its a bug. I'm just curious because when I was testing, I never ran into anything like that.

So could you please clarify thanks :)

**Comment by Nesseley** [comment]
`the countdown while people are hiding` That one, it just sticks in the waiting for players to join, and doesn't change when the game starts.

**Comment by tylermurphy534** [comment]
Im not sure what is causing your issue, as I am unable to reproduce it.
![lobby](https://user-images.githubusercontent.com/28487599/169537440-54fd6cce-e19c-4be6-9d5f-f2caa9f9d76d.png)
![game play](https://user-images.githubusercontent.com/28487599/169537446-3cde2106-e606-42d7-a045-893c14d6e756.png)

**Comment by Nesseley** [comment]
How weird! I will be doing some testing.

**Comment by Nesseley** [comment]
The bug appears only when:

glow: is set to `enabled: false`
Or if you set `alwaysGlow: true`

**Comment by tylermurphy534** [comment]
Hopefully fixed in 1.5.0 Release Candidate 4. I had a misplaced `return` keyword instead of `continue`....

**Comment by Nesseley** [comment]
Fixed
