### ISSUE TITLE
Bug report/Feature Request: Titelscreen <TEAM> needs 1-2 second more before countdown starts

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#61]
**Describe the bug**
The title for what team you get is interrupted by the countdown if you have it set to title.

**Expected behavior**
It would be better if the countdown is run 1-2 seconds later so people have time to read the title message.

**System Info (please complete the following information):**
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2349216702

**Comment by tylermurphy534** [comment]
Fix attempt in 1.5.0 Release Candidate 3

**Comment by Nesseley** [comment]
Looks good to me!
