### ISSUE TITLE
Bug Report: CRITICAL: Blindness, jump boost and slowness not removed on game start

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#64]
**Describe the bug**
The seeker doesn't get cleared for the effects when game starts. And therefore can't move or seek for anyone :P 

**System Info (please complete the following information):**
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2380075203

**Comment by bobby29831** [comment]
Actually fixed by "[1.5.0 Release Candidate 4.1](https://github.com/tylermurphy534/KenshinsHideAndSeek/commit/a05ba6d1494f1ba0944c1e66a12a72405a2c9a7f)"

**Comment by Nesseley** [comment]
Fixed :D
