### ISSUE TITLE
Bug Report: CRITICAL! Plugin disables damage on the entire server.

### ISSUE THREAD

**Issue by Nesseley** [tylermurphy534/KenshinsHideAndSeek#66]
**Describe the bug**
When the plugin is installed it disables damage on my entire server. I don't take damage from mobs at all, or fall damage. I'm invincible. 

**Expected behavior**
The plugin shouldn't effect the rest of the server, just players in the hide and seek arena.

**System Info (please complete the following information):**
 - Plugin Version [e.g. 1.3.0/1.3.1 BETA] https://github.com/tylermurphy534/KenshinsHideAndSeek/actions/runs/2387751044

**Comment by tylermurphy534** [comment]
Uploaded a fix, there was an oversight for when pvpEnabled was false.

**Comment by Nesseley** [comment]
Not fixed. I hear dmg sounds, but take no damage. 
I think your plugin tried to insta-kill me and send me to the hs warp. I am testing dmg in a MobArena, and it spams that im not allowed to teleport bc your plugin tried to send me somewhere

**Comment by tylermurphy534** [comment]
Im dumb lol, attempted another fix. Sorry for the lack of testing, as I cant really test stuff right now (in school), and I believe you want fixes ASAP.

**Comment by Nesseley** [comment]
Now I don't take damage again, but the teleport message is gone

**Comment by tylermurphy534** [comment]
Are you in the Hide and Seek lobby when testing?

**Comment by tylermurphy534** [comment]
uploaded RC4.2c

**Comment by Nesseley** [comment]
I was in a minigame called MobArena :)

Fixed! 🎉
