### ISSUE TITLE
Leaving the game lobby will cause the player's inventory to be emptied

### ISSUE THREAD

**Issue by BZX6666** [tylermurphy534/KenshinsHideAndSeek#70]
**Describe the bug**
Leaving the game lobby will cause the player's inventory to be emptied.
**To Reproduce**
1./hs join
2.click leave lobby

**Expected behavior**
players should get what they have before join the game
**Screenshots**

**System Info (please complete the following information):**
 - Linux[e.g. Windows/Linux]
 - Custom [e.g. Apex/Custom]
 - 1.19[e.g. 1.17/1.18]
 - latest[e.g. 1.3.0/1.3.1 BETA]

**Additional context**

**Comment by BZX6666** [comment]
version 1.5.0

**Comment by tylermurphy534** [comment]
Uploaded a BETA for 1.5.1 that adds this feature. I tested it myself and It seems to work, feel free to test it yourself :)

**Comment by BZX6666** [comment]
thanks
