### ISSUE TITLE
Seeker turned into a block during testing

### ISSUE THREAD

**Issue by Vilsu221** [tylermurphy534/KenshinsHideAndSeek#75]
**Describe the bug**
After Joining the game, in testing we quickly noticed how the seeker had also been turned into a block. However, dying as a seeker fixes the bug.

**Screenshots**
![2022-08-17_00 52 48](https://user-images.githubusercontent.com/58680173/184992054-5cbfd44b-3155-463f-8e1a-7c300e70a91a.png)

**System Info (please complete the following information):**
 - OS: [Linux]
 - Server Host [Custom]
 - MC Version [1.19]
 - Plugin Version [1.6.0]

**Comment by tylermurphy534** [comment]
By turning into a block, do they get the popup menu to select a block? Do they just turn into a block at random? Is It a block they selected from previous rounds?

**Comment by Vilsu221** [comment]
They did NOT get the hider's popup menu, and it unfortunately isn't 100% clear if it was from previous rounds.

**Comment by tylermurphy534** [comment]
Interesting because I literally have no idea why this is happening on your end. For all the testing myself and other people using the plugin have done, this hasn't been an issue. Is there anything at all that you think could be causing this? Can you also send your config files and server log.

**Comment by Vilsu221** [comment]
The plugin doesn't seem to have detected it as an issue, so there's nothing unusual in the logs atleast

[Confignlog.zip](https://github.com/tylermurphy534/KenshinsHideAndSeek/files/9359576/Confignlog.zip)

**Comment by tylermurphy534** [comment]
I have no idea what is causing this as I am unable to replicate it. Can you send what plugins you are using?

**Comment by Vilsu221** [comment]
![image](https://user-images.githubusercontent.com/58680173/185236473-c13288bf-a947-449d-81be-aad6d28e124f.png)

**Comment by tylermurphy534** [comment]
Can you try removing plugins and then testing again, because I am completely unable to replicate this from my end. I have absolutely why this i happening. My guess would be GriefPrevention.
