### ISSUE TITLE
Missing SEEKER_SPAWN

### ISSUE THREAD

**Issue by Vilsu221** [tylermurphy534/KenshinsHideAndSeek#77]
**Describe the bug**
Plugin complains about SEEKER_SPAWN missing from localization.yml

**Expected behavior**
I tried to use /setseekerlobby command

**Screenshots**
![unknown](https://user-images.githubusercontent.com/58680173/185153891-8977782d-af7d-471e-b827-0aec26f50b03.png)

**System Info (please complete the following information):**
 - OS: [Linux]
 - Server Host [Custom]
 - MC Version [1.19]
 - Plugin Version [1.6.1]

**Comment by tylermurphy534** [comment]
fixed in 1.6.2 beta
