### ISSUE TITLE
Respawn timer's time not shown

### ISSUE THREAD

**Issue by Vilsu221** [tylermurphy534/KenshinsHideAndSeek#78]
**Screenshots**
![unknown](https://user-images.githubusercontent.com/58680173/185155340-7f17e214-663e-418f-a129-8b5c43a83643.png)

**System Info (please complete the following information):**
 - OS: [Linux]
 - Server Host [Custom]
 - MC Version [1.19]
 - Plugin Version [1.6.1]

**Comment by tylermurphy534** [comment]
fixed in 1.6.2 beta
