### ISSUE TITLE
New blocks not recognised as blocks by plugin

### ISSUE THREAD

**Issue by Vilsu221** [tylermurphy534/KenshinsHideAndSeek#80]
**Describe the bug**
1.19 materials are not recognised by the plugin as hider blocks.

**Screenshots**
![unknown3](https://user-images.githubusercontent.com/58680173/185173740-5b52dec5-c7a6-4e33-9364-c250ec9c9459.png)
![unknown2](https://user-images.githubusercontent.com/58680173/185173746-1a244e3c-217f-44b5-8722-11cca5402138.png)

**System Info (please complete the following information):**
 - OS: [Linux]
 - Server Host [Custom]
 - MC Version [1.19]
 - Plugin Version [1.6.1]

**Comment by tylermurphy534** [comment]
fixed in 1.6.2 beta
