### ISSUE TITLE
Submit zh-CN language file

### ISSUE THREAD

**Issue by Xiaye2332** [tylermurphy534/KenshinsHideAndSeek#82]
**Describe the solution you'd like**
Hey, it's really a nice plugin, and it seems not support Chinese, so I do this. :)

Here is DropBox url [https://www.dropbox.com/s/0it5vjt6f3u4p8y/localization_zh-CN.yml?dl=0](url)

Localization:
  COMMAND_PLAYER_ONLY: "该指令仅能由玩家执行"
  COMMAND_NOT_ALLOWED: "你没有使用此命令的权限"
  COMMAND_ERROR: "出现了内部错误"
  GAME_PLAYER_DEATH: "&c{PLAYER}&f 被击杀了"
  GAME_PLAYER_FOUND: "&e{PLAYER}&f 被找到了并已成为寻找者"
  GAME_PLAYER_FOUND_BY: "&e{PLAYER}&f 被 &c{PLAYER}&f 找到了并已成为寻找者"
  GAME_GAMEOVER_HIDERS_FOUND: "所有人都被发现了"
  GAME_GAMEOVER_SEEKERS_QUIT: "所有寻找者都离开了"
  GAME_GAMEOVER_HIDERS_QUIT: "所有躲藏者都离开了"
  GAME_GAMEOVER_TIME: "时间结束,躲藏者获胜"
  GAME_SETUP: "游戏已完成设置, 使用 /hs setup 查看下一步"
  GAME_INGAME: "你已经在游戏中了"
  GAME_NOT_INGAME: "你还不在游戏中"
  GAME_INPROGRESS: "游戏已经开始了"
  GAME_NOT_INPROGRESS: "没有正在进行中的游戏"
  GAME_JOIN: "{PLAYER} 加入了躲猫猫游戏"
  GAME_JOIN_SPECTATOR: "中场加入,将作为旁观者进行游戏"
  GAME_LEAVE: "{PLAYER} 离开了躲猫猫游戏"
  CONFIG_RELOAD: "配置已重载"
  MAPSAVE_INPROGRESS: "地图正在保存中，请稍后"
  MAPSAVE_START: "地图开始保存"
  MAPSAVE_WARNING: "地图保存过程中无法使用指令,请勿关闭服务器"
  MAPSAVE_END: "地图保存成功"
  MAPSAVE_ERROR: "找不到当前地图"
  MAPSAVE_DISABLED: "地图保存已在config中关闭"
  WORLDBORDER_DISABLE: "关闭世界边界"
  WORLDBORDER_INVALID_INPUT: "无效的数量"
  WORLDBORDER_MIN_SIZE: "世界边界应当大于100"
  WORLDBORDER_POSITION: "出生点应当在边界100格范围内"
  WORLDBORDER_ENABLE: "将边界设定到目前位置,大小为 {AMOUNT} 格, 延时 {AMOUNT}, 移动到 {AMOUNT}."
  WORLDBORDER_DECREASING: "世界边界将在30秒内缩小 {AMOUNT} 格"
  WORLDBORDER_WARN: "世界边界将在30秒后缩小"
  WORLDBORDER_CHANGE_SIZE: "世界边界变化无法小于0"
  TAUNTED: "&c&o你被选为了嘲讽者!"
  TAUNT: "将在30秒后随机抽选一名躲藏者嘲讽"
  TAUNT_ACTIVATE: "嘲讽已生效"
  ERROR_GAME_SPAWN: "请先设置游戏出生点"
  SETUP: "&f&l此项还没有完成设置"
  SETUP_GAME: "&c&l- &f请使用 /hs setspawn 设置游戏出生点"
  SETUP_LOBBY: "&c&l- &f请使用 /hs setlobby 设置游戏大厅位置"
  SETUP_SEEKER_LOBBY: "&c&l- &f请使用 /hs setseekerlobby 设置寻找者出生点"
  SETUP_EXIT: "&c&l- &f使用 /hs setexit 设置退出游戏后的传送地点"
  SETUP_SAVEMAP: "&c&l- &f地图还未保存, 请使用 /hs savemap 保存地图 (先 /hs setspawn)"
  SETUP_BOUNDS: "&c&l- &f请使用 /hs setbounds 设置两个对角线地图边界"
  SETUP_COMPLETE: "所有设置已完成!"
  GAME_SPAWN: "设置游戏出生点"
  LOBBY_SPAWN: "已设置大厅位置"
  EXIT_SPAWN: "已设置离开地点"
  SEEKER_SPAWN: "已设置寻找者出生点"
  START_MIN_PLAYERS: "至少要有 {AMOUNT} 名玩家才能开始"
  START_INVALID_NAME: "错误的玩家名: {PLAYER}."
  START_COUNTDOWN: "躲藏者还有 {AMOUNT} 秒躲藏时间!"
  START_COUNTDOWN_LAST: "还有 {AMOUNT} 秒躲藏时间!"
  START: "开始寻找"
  STOP: "游戏已被终止"
  HIDER_TEAM_NAME: "&6&l寻找者"
  SEEKER_TEAM_NAME: "&c&l躲藏者"
  SPECTATOR_TEAM_NAME: "&8&l旁观者"
  HIDERS_SUBTITLE: "躲藏至游戏结束"
  SEEKERS_SUBTITLE: "找到所有躲藏者"
  SPECTATOR_SUBTITLE: "成功中途加入"
  BOUNDS_WRONG_WORLD: "请在游戏世界中使用此指令"
  BOUNDS: "成功在 ({AMOUNT}/2) 设置了边界"
  NOT_AT_ZERO: "请勿将坐标设置在0的位置"
  NO_GAME_INFO: "该玩家没有游玩数据"
  INFORMATION_FOR: "玩家 {PLAYER} 的获胜数据:"
  BLOCKED_COMMAND: "由躲猫猫插件阻止的指令"
  FLYING_ENABLED: "&l&b飞行开始"
  FLYING_DISABLED: "&l&b飞行结束"
  RESPAWN_NOTICE: "将在 {AMOUNT} 秒后复活"

**Comment by tylermurphy534** [comment]
Thank you so much. If you want, you can send this as a git pull request so that you can be marked as a contributor on the repo.

**Comment by Xiaye2332** [comment]
Yes, it's done.
